global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy-lb1:80', 'haproxy-lb2:80', 'haproxy-lb3:80']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend-api1:5000', 'backend-api2:5000', 'backend-api3:5000']
